Traceback (most recent call last):
  File "/Users/ckim/miniconda3/envs/astro-tigress/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ckim/miniconda3/envs/astro-tigress/lib/python3.8/site-packages/nbclient/client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ckim/miniconda3/envs/astro-tigress/lib/python3.8/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/ckim/miniconda3/envs/astro-tigress/lib/python3.8/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/Users/ckim/miniconda3/envs/astro-tigress/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/ckim/miniconda3/envs/astro-tigress/lib/python3.8/site-packages/nbclient/client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "/Users/ckim/miniconda3/envs/astro-tigress/lib/python3.8/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ckim/miniconda3/envs/astro-tigress/lib/python3.8/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print("Snapshots and contained data sets:")
for ivtk in model.ivtks:
    print("ivtk={:d}, t={:.1f} Myr, datasets={}".format(ivtk, ivtk*model.dt_Myr, model.data_sets[ivtk]))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn [4], line 2[0m
[1;32m      1[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mSnapshots and contained data sets:[39m[38;5;124m"[39m)
[0;32m----> 2[0m [38;5;28;01mfor[39;00m ivtk [38;5;129;01min[39;00m [43mmodel[49m[38;5;241;43m.[39;49m[43mivtks[49m:
[1;32m      3[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mivtk=[39m[38;5;132;01m{:d}[39;00m[38;5;124m, t=[39m[38;5;132;01m{:.1f}[39;00m[38;5;124m Myr, datasets=[39m[38;5;132;01m{}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(ivtk, ivtk[38;5;241m*[39mmodel[38;5;241m.[39mdt_Myr, model[38;5;241m.[39mdata_sets[ivtk]))

[0;31mAttributeError[0m: 'Model' object has no attribute 'ivtks'
AttributeError: 'Model' object has no attribute 'ivtks'

